# Site settings
title: website title
domain: orionaskatu.github.io
email: your@email.com
description: "website"

# Google Tag Manager Id
gtmId: GTM-TAGID

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '2a9d8f'
  secondary: 'f4a261'
  secondary-dark: 'e76f51'
  
# Footer settings
footer:
  copyright: copyright

# Build settings
markdown: kramdown
permalink: pretty

# Social settings
facebook_url: myaccount
twitter_url: myaccount
linkedin_url: myaccount
googleplus_url: myaccount
pinterest_url: myaccount
instagram_url: myaccount