# Site settings
title: website title
domain: orionaskatu.github.io
email: your@email.com
description: "website"

# Google Tag Manager Id
gtmId: GTM-TAGID

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '000000'
  secondary: '2c3651'
  secondary-dark: '2c3651'
  
# Footer settings
footer:
  copyright: copyright

# Build settings
markdown: kramdown
permalink: pretty
