# Site settings
title: website title
domain: orionaskatu.github.io
email: your@email.com
description: "website"

# Google Tag Manager Id
gtmId: GTM-TAGID

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: '3d405b'
  secondary: '006d77'
  secondary-dark: 'e76f51'
  
# Footer settings
footer:
  copyright: copyright

# Build settings
markdown: kramdown
permalink: pretty

# Social settings
facebook_url: myaccount
instagram_url: myaccount
kofi_url: myaccount
inprnt_url: myaccount
spoonflower_url: myaccount